-- MySQL Script generated by MySQL Workbench
-- Sun Nov 19 13:19:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema equipe<494871>
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema equipe<494871>
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `equipe<494871>` ;
USE `equipe<494871>` ;

-- -----------------------------------------------------
-- Table `equipe<494871>`.`AGENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`AGENCIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `salario_montante_total` DECIMAL(18,2) NULL,
  `cidade` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`FUNCIONARIOS` (
  `matricula_login` INT NOT NULL AUTO_INCREMENT,
  `AGENCIA_ID` INT NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `cargo` ENUM('gerente', 'atendente', 'caixa') NOT NULL,
  `salario` DECIMAL(18,2) NOT NULL,
  `nome` VARCHAR(50) NULL,
  `endereço` VARCHAR(60) NULL,
  `cidade` VARCHAR(20) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`matricula_login`, `AGENCIA_ID`),
  INDEX `fk_FUNCIONARIOS_AGENCIA1_idx` (`AGENCIA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_FUNCIONARIOS_AGENCIA1`
    FOREIGN KEY (`AGENCIA_ID`)
    REFERENCES `equipe<494871>`.`AGENCIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`DEPENDENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`DEPENDENTES` (
  `nome` VARCHAR(50) NOT NULL,
  `FUNCIONARIOS_matricula_login` INT NOT NULL,
  `data_nascimento` DATE NULL,
  `parentesco` ENUM('filho', 'filha', 'conjuge', 'genitor', 'genitora') NULL,
  `idade` INT NULL,
  PRIMARY KEY (`nome`, `FUNCIONARIOS_matricula_login`),
  INDEX `fk_DEPENDENTES_FUNCIONARIOS1_idx` (`FUNCIONARIOS_matricula_login` ASC) VISIBLE,
  CONSTRAINT `fk_DEPENDENTES_FUNCIONARIOS1`
    FOREIGN KEY (`FUNCIONARIOS_matricula_login`)
    REFERENCES `equipe<494871>`.`FUNCIONARIOS` (`matricula_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`CONTAS_BANCARIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`CONTAS_BANCARIAS` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `AGENCIA_ID` INT NOT NULL,
  `gerente_mat` INT NOT NULL,
  `saldo` DECIMAL(18,2) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `tipo_conta` ENUM('poupanca', 'corrente', 'especial') NOT NULL,
  PRIMARY KEY (`numero`, `AGENCIA_ID`),
  INDEX `fk_CONTAS_BANCARIAS_FUNCIONARIOS1_idx` (`gerente_mat` ASC) VISIBLE,
  INDEX `fk_CONTAS_BANCARIAS_AGENCIA1_idx` (`AGENCIA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CONTAS_BANCARIAS_FUNCIONARIOS1`
    FOREIGN KEY (`gerente_mat`)
    REFERENCES `equipe<494871>`.`FUNCIONARIOS` (`matricula_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTAS_BANCARIAS_AGENCIA1`
    FOREIGN KEY (`AGENCIA_ID`)
    REFERENCES `equipe<494871>`.`AGENCIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`CLIENTES` (
  `CPF` CHAR(11) NOT NULL,
  `tipo_titular` ENUM('principal', 'co-titular') NOT NULL,
  `CONTAS_BANCARIAS_numero` INT NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(50) NULL,
  `RG` VARCHAR(15) NULL,
  `orgao_emissor` VARCHAR(30) NULL,
  `UF` CHAR(2) NULL,
  `data_nascimento` DATE NULL,
  `tipo_logradouro` VARCHAR(20) NULL,
  `nome_logradouro` VARCHAR(40) NULL,
  `numero` VARCHAR(8) NULL,
  `bairro` VARCHAR(30) NULL,
  `CEP` CHAR(8) NULL,
  `cidade` VARCHAR(20) NULL,
  `estado` VARCHAR(20) NULL,
  PRIMARY KEY (`CPF`, `CONTAS_BANCARIAS_numero`, `tipo_titular`),
  INDEX `fk_CLIENTES_CONTAS_BANCARIAS1_idx` (`CONTAS_BANCARIAS_numero` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_CONTAS_BANCARIAS1`
    FOREIGN KEY (`CONTAS_BANCARIAS_numero`)
    REFERENCES `equipe<494871>`.`CONTAS_BANCARIAS` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`TRANSACOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`TRANSACOES` (
  `numero_transacao` INT NOT NULL AUTO_INCREMENT,
  `CONTAS_BANCARIAS_numero` INT NOT NULL,
  `tipo_transacao` ENUM('saque', 'deposito', 'pagamento', 'estorno', 'transferencia') NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`numero_transacao`),
  INDEX `fk_TRANSACOES_CONTAS_BANCARIAS1_idx` (`CONTAS_BANCARIAS_numero` ASC) VISIBLE,
  CONSTRAINT `fk_TRANSACOES_CONTAS_BANCARIAS1`
    FOREIGN KEY (`CONTAS_BANCARIAS_numero`)
    REFERENCES `equipe<494871>`.`CONTAS_BANCARIAS` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`TELEFONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`TELEFONES` (
  `telefone` VARCHAR(11) NOT NULL,
  `CLIENTES_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`telefone`, `CLIENTES_CPF`),
  INDEX `fk_TELEFONES_CLIENTES1_idx` (`CLIENTES_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFONES_CLIENTES1`
    FOREIGN KEY (`CLIENTES_CPF`)
    REFERENCES `equipe<494871>`.`CLIENTES` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`EMAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`EMAILS` (
  `email` VARCHAR(60) NOT NULL,
  `CLIENTES_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`email`, `CLIENTES_CPF`),
  INDEX `fk_EMAILS_CLIENTES1_idx` (`CLIENTES_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_EMAILS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_CPF`)
    REFERENCES `equipe<494871>`.`CLIENTES` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`CONTA_CORRENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`CONTA_CORRENTE` (
  `CONTAS_BANCARIAS_numero` INT NOT NULL,
  `data_aniversario` DATE NOT NULL,
  PRIMARY KEY (`CONTAS_BANCARIAS_numero`),
  CONSTRAINT `fk_CONTA_CORRENTE_CONTAS_BANCARIAS1`
    FOREIGN KEY (`CONTAS_BANCARIAS_numero`)
    REFERENCES `equipe<494871>`.`CONTAS_BANCARIAS` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`CONTA_POUPANCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`CONTA_POUPANCA` (
  `CONTAS_BANCARIAS_numero` INT NOT NULL,
  `taxa_juros` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`CONTAS_BANCARIAS_numero`),
  CONSTRAINT `fk_CONTA_POUPANCA_CONTAS_BANCARIAS1`
    FOREIGN KEY (`CONTAS_BANCARIAS_numero`)
    REFERENCES `equipe<494871>`.`CONTAS_BANCARIAS` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipe<494871>`.`CONTA_ESPECIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipe<494871>`.`CONTA_ESPECIAL` (
  `CONTAS_BANCARIAS_numero` INT NOT NULL,
  `limite_credito` FLOAT NOT NULL,
  PRIMARY KEY (`CONTAS_BANCARIAS_numero`),
  CONSTRAINT `fk_CONTA_ESPECIAL_CONTAS_BANCARIAS1`
    FOREIGN KEY (`CONTAS_BANCARIAS_numero`)
    REFERENCES `equipe<494871>`.`CONTAS_BANCARIAS` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
